/*
 * Unique SDK
 *
 * Unique SDK HTTP API  <b>Main connection to wss://ws-opal.unique.network (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-opal.unique.network\">apps ↗</a>)</b>  Secondary substrate connection to wss://ws-relay-bench.unique.network  (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-relay-bench.unique.network\">apps ↗</a>). Go to <a href=\"/relay/swagger\">/relay/swagger</a>  Consumable OpenAPI specification - (<a target=\"_blank\" href=\"/swagger-json\">JSON ↗</a>) (<a target=\"_blank\" href=\"/swagger-yaml\">YAML ↗</a>)
 *
 * The version of the OpenAPI document: 0.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CollectionFlags
    /// </summary>
    [DataContract(Name = "CollectionFlags")]
    public partial class CollectionFlags : IEquatable<CollectionFlags>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionFlags" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CollectionFlags() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionFlags" /> class.
        /// </summary>
        /// <param name="foreign">foreign (required).</param>
        /// <param name="erc721metadata">erc721metadata (required).</param>
        public CollectionFlags(bool foreign = default(bool), bool erc721metadata = default(bool))
        {
            this.Foreign = foreign;
            this.Erc721metadata = erc721metadata;
        }

        /// <summary>
        /// Gets or Sets Foreign
        /// </summary>
        [DataMember(Name = "foreign", IsRequired = true, EmitDefaultValue = true)]
        public bool Foreign { get; set; }

        /// <summary>
        /// Gets or Sets Erc721metadata
        /// </summary>
        [DataMember(Name = "erc721metadata", IsRequired = true, EmitDefaultValue = true)]
        public bool Erc721metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CollectionFlags {\n");
            sb.Append("  Foreign: ").Append(Foreign).Append("\n");
            sb.Append("  Erc721metadata: ").Append(Erc721metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CollectionFlags);
        }

        /// <summary>
        /// Returns true if CollectionFlags instances are equal
        /// </summary>
        /// <param name="input">Instance of CollectionFlags to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CollectionFlags input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Foreign == input.Foreign ||
                    this.Foreign.Equals(input.Foreign)
                ) && 
                (
                    this.Erc721metadata == input.Erc721metadata ||
                    this.Erc721metadata.Equals(input.Erc721metadata)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Foreign.GetHashCode();
                hashCode = (hashCode * 59) + this.Erc721metadata.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
