/*
 * Unique SDK
 *
 * Unique SDK HTTP API  <b>Main connection to wss://ws-opal.unique.network (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-opal.unique.network\">apps ↗</a>)</b>  Secondary substrate connection to wss://ws-relay-bench.unique.network  (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-relay-bench.unique.network\">apps ↗</a>). Go to <a href=\"/relay/swagger\">/relay/swagger</a>  Consumable OpenAPI specification - (<a target=\"_blank\" href=\"/swagger-json\">JSON ↗</a>) (<a target=\"_blank\" href=\"/swagger-yaml\">YAML ↗</a>)
 *
 * The version of the OpenAPI document: 0.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Network.Unique.API.Client.OpenAPIDateConverter;

namespace Network.Unique.API.Model
{
    /// <summary>
    /// DecodedAttributeDtoRawValueOneOf
    /// </summary>
    [DataContract(Name = "DecodedAttributeDto_rawValue_oneOf")]
    public partial class DecodedAttributeDtoRawValueOneOf : Dictionary<String, string>, IEquatable<DecodedAttributeDtoRawValueOneOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DecodedAttributeDtoRawValueOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DecodedAttributeDtoRawValueOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DecodedAttributeDtoRawValueOneOf" /> class.
        /// </summary>
        /// <param name=""> (required).</param>
        public DecodedAttributeDtoRawValueOneOf(string args = default(string)) : base()
        {
            // to ensure "" is required (not null)
            if (args == null)
            {
                throw new ArgumentNullException(" is a required property for DecodedAttributeDtoRawValueOneOf and cannot be null");
            }
            this._args = args;
        }

        /// <summary>
        /// Gets or Sets _
        /// </summary>
        [DataMember(Name = "_", IsRequired = true, EmitDefaultValue = true)]
        public string _args { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DecodedAttributeDtoRawValueOneOf {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  _: ").Append(_args).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DecodedAttributeDtoRawValueOneOf);
        }

        /// <summary>
        /// Returns true if DecodedAttributeDtoRawValueOneOf instances are equal
        /// </summary>
        /// <param name="input">Instance of DecodedAttributeDtoRawValueOneOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DecodedAttributeDtoRawValueOneOf input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this._args == input._args ||
                    (this._args != null &&
                    this._args.Equals(input._args))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this._args != null)
                {
                    hashCode = (hashCode * 59) + this._args.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
