/*
 * Unique SDK
 *
 * Unique SDK HTTP API  <b>Main connection to wss://ws-opal.unique.network (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-opal.unique.network\">apps ↗</a>)</b>  Secondary substrate connection to wss://ws-relay-bench.unique.network  (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-relay-bench.unique.network\">apps ↗</a>). Go to <a href=\"/relay/swagger\">/relay/swagger</a>  Consumable OpenAPI specification - (<a target=\"_blank\" href=\"/swagger-json\">JSON ↗</a>) (<a target=\"_blank\" href=\"/swagger-yaml\">YAML ↗</a>)
 *
 * The version of the OpenAPI document: 0.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Network.Unique.API.Client.OpenAPIDateConverter;

namespace Network.Unique.API.Model
{
    /// <summary>
    /// RemoveFromAllowListBody
    /// </summary>
    [DataContract(Name = "RemoveFromAllowListBody")]
    public partial class RemoveFromAllowListBody : IEquatable<RemoveFromAllowListBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveFromAllowListBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemoveFromAllowListBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveFromAllowListBody" /> class.
        /// </summary>
        /// <param name="collectionId">collectionId (required).</param>
        /// <param name="address">The ss-58 encoded address (required).</param>
        /// <param name="addressToDelete">The ss-58 encoded address (required).</param>
        public RemoveFromAllowListBody(decimal collectionId = default(decimal), string address = default(string), string addressToDelete = default(string))
        {
            this.CollectionId = collectionId;
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for RemoveFromAllowListBody and cannot be null");
            }
            this.Address = address;
            // to ensure "addressToDelete" is required (not null)
            if (addressToDelete == null)
            {
                throw new ArgumentNullException("addressToDelete is a required property for RemoveFromAllowListBody and cannot be null");
            }
            this.AddressToDelete = addressToDelete;
        }

        /// <summary>
        /// Gets or Sets CollectionId
        /// </summary>
        [DataMember(Name = "collectionId", IsRequired = true, EmitDefaultValue = true)]
        public decimal CollectionId { get; set; }

        /// <summary>
        /// The ss-58 encoded address
        /// </summary>
        /// <value>The ss-58 encoded address</value>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        /// The ss-58 encoded address
        /// </summary>
        /// <value>The ss-58 encoded address</value>
        [DataMember(Name = "addressToDelete", IsRequired = true, EmitDefaultValue = true)]
        public string AddressToDelete { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveFromAllowListBody {\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  AddressToDelete: ").Append(AddressToDelete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RemoveFromAllowListBody);
        }

        /// <summary>
        /// Returns true if RemoveFromAllowListBody instances are equal
        /// </summary>
        /// <param name="input">Instance of RemoveFromAllowListBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemoveFromAllowListBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectionId == input.CollectionId ||
                    this.CollectionId.Equals(input.CollectionId)
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.AddressToDelete == input.AddressToDelete ||
                    (this.AddressToDelete != null &&
                    this.AddressToDelete.Equals(input.AddressToDelete))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CollectionId.GetHashCode();
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.AddressToDelete != null)
                {
                    hashCode = (hashCode * 59) + this.AddressToDelete.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
