/*
 * Unique SDK
 *
 * Unique SDK HTTP API  <b>Main connection to wss://ws-opal.unique.network (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-opal.unique.network\">apps ↗</a>)</b>  Secondary substrate connection to wss://ws-relay-bench.unique.network  (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-relay-bench.unique.network\">apps ↗</a>). Go to <a href=\"/relay/swagger\">/relay/swagger</a>  Consumable OpenAPI specification - (<a target=\"_blank\" href=\"/swagger-json\">JSON ↗</a>) (<a target=\"_blank\" href=\"/swagger-yaml\">YAML ↗</a>)
 *
 * The version of the OpenAPI document: 0.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Network.Unique.API.Client.OpenAPIDateConverter;

namespace Network.Unique.API.Model
{
    /// <summary>
    /// TopmostTokenOwnerResponse
    /// </summary>
    [DataContract(Name = "TopmostTokenOwnerResponse")]
    public partial class TopmostTokenOwnerResponse : IEquatable<TopmostTokenOwnerResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TopmostTokenOwnerResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TopmostTokenOwnerResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TopmostTokenOwnerResponse" /> class.
        /// </summary>
        /// <param name="topmostOwner">The ss-58 encoded address (required).</param>
        public TopmostTokenOwnerResponse(string topmostOwner = default(string))
        {
            // to ensure "topmostOwner" is required (not null)
            if (topmostOwner == null)
            {
                throw new ArgumentNullException("topmostOwner is a required property for TopmostTokenOwnerResponse and cannot be null");
            }
            this.TopmostOwner = topmostOwner;
        }

        /// <summary>
        /// The ss-58 encoded address
        /// </summary>
        /// <value>The ss-58 encoded address</value>
        [DataMember(Name = "topmostOwner", IsRequired = true, EmitDefaultValue = true)]
        public string TopmostOwner { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TopmostTokenOwnerResponse {\n");
            sb.Append("  TopmostOwner: ").Append(TopmostOwner).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TopmostTokenOwnerResponse);
        }

        /// <summary>
        /// Returns true if TopmostTokenOwnerResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TopmostTokenOwnerResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TopmostTokenOwnerResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TopmostOwner == input.TopmostOwner ||
                    (this.TopmostOwner != null &&
                    this.TopmostOwner.Equals(input.TopmostOwner))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TopmostOwner != null)
                {
                    hashCode = (hashCode * 59) + this.TopmostOwner.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
