/*
 * Unique SDK
 *
 * Unique SDK HTTP API  <b>Main connection to wss://ws-opal.unique.network (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-opal.unique.network\">apps ↗</a>)</b>  Secondary substrate connection to wss://ws-relay-bench.unique.network  (<a target=\"_blank\" href=\"https://polkadot.js.org/apps/?rpc=wss://ws-relay-bench.unique.network\">apps ↗</a>). Go to <a href=\"/relay/swagger\">/relay/swagger</a>  Consumable OpenAPI specification - (<a target=\"_blank\" href=\"/swagger-json\">JSON ↗</a>) (<a target=\"_blank\" href=\"/swagger-yaml\">YAML ↗</a>)
 *
 * The version of the OpenAPI document: 0.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Network.Unique.API.Client.OpenAPIDateConverter;

namespace Network.Unique.API.Model
{
    /// <summary>
    /// UnsignedTxPayloadResponse
    /// </summary>
    [DataContract(Name = "UnsignedTxPayloadResponse")]
    public partial class UnsignedTxPayloadResponse : IEquatable<UnsignedTxPayloadResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsignedTxPayloadResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UnsignedTxPayloadResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsignedTxPayloadResponse" /> class.
        /// </summary>
        /// <param name="signerPayloadJSON">signerPayloadJSON (required).</param>
        /// <param name="signerPayloadRaw">signerPayloadRaw (required).</param>
        /// <param name="signerPayloadHex">signerPayloadHex (required).</param>
        /// <param name="fee">fee.</param>
        public UnsignedTxPayloadResponse(SignerPayloadJSONDto signerPayloadJSON = default(SignerPayloadJSONDto), SignerPayloadRawDto signerPayloadRaw = default(SignerPayloadRawDto), string signerPayloadHex = default(string), FeeResponse fee = default(FeeResponse))
        {
            // to ensure "signerPayloadJSON" is required (not null)
            if (signerPayloadJSON == null)
            {
                throw new ArgumentNullException("signerPayloadJSON is a required property for UnsignedTxPayloadResponse and cannot be null");
            }
            this.SignerPayloadJSON = signerPayloadJSON;
            // to ensure "signerPayloadRaw" is required (not null)
            if (signerPayloadRaw == null)
            {
                throw new ArgumentNullException("signerPayloadRaw is a required property for UnsignedTxPayloadResponse and cannot be null");
            }
            this.SignerPayloadRaw = signerPayloadRaw;
            // to ensure "signerPayloadHex" is required (not null)
            if (signerPayloadHex == null)
            {
                throw new ArgumentNullException("signerPayloadHex is a required property for UnsignedTxPayloadResponse and cannot be null");
            }
            this.SignerPayloadHex = signerPayloadHex;
            this.Fee = fee;
        }

        /// <summary>
        /// Gets or Sets SignerPayloadJSON
        /// </summary>
        [DataMember(Name = "signerPayloadJSON", IsRequired = true, EmitDefaultValue = true)]
        public SignerPayloadJSONDto SignerPayloadJSON { get; set; }

        /// <summary>
        /// Gets or Sets SignerPayloadRaw
        /// </summary>
        [DataMember(Name = "signerPayloadRaw", IsRequired = true, EmitDefaultValue = true)]
        public SignerPayloadRawDto SignerPayloadRaw { get; set; }

        /// <summary>
        /// Gets or Sets SignerPayloadHex
        /// </summary>
        [DataMember(Name = "signerPayloadHex", IsRequired = true, EmitDefaultValue = true)]
        public string SignerPayloadHex { get; set; }

        /// <summary>
        /// Gets or Sets Fee
        /// </summary>
        [DataMember(Name = "fee", EmitDefaultValue = false)]
        public FeeResponse Fee { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnsignedTxPayloadResponse {\n");
            sb.Append("  SignerPayloadJSON: ").Append(SignerPayloadJSON).Append("\n");
            sb.Append("  SignerPayloadRaw: ").Append(SignerPayloadRaw).Append("\n");
            sb.Append("  SignerPayloadHex: ").Append(SignerPayloadHex).Append("\n");
            sb.Append("  Fee: ").Append(Fee).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UnsignedTxPayloadResponse);
        }

        /// <summary>
        /// Returns true if UnsignedTxPayloadResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of UnsignedTxPayloadResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnsignedTxPayloadResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SignerPayloadJSON == input.SignerPayloadJSON ||
                    (this.SignerPayloadJSON != null &&
                    this.SignerPayloadJSON.Equals(input.SignerPayloadJSON))
                ) && 
                (
                    this.SignerPayloadRaw == input.SignerPayloadRaw ||
                    (this.SignerPayloadRaw != null &&
                    this.SignerPayloadRaw.Equals(input.SignerPayloadRaw))
                ) && 
                (
                    this.SignerPayloadHex == input.SignerPayloadHex ||
                    (this.SignerPayloadHex != null &&
                    this.SignerPayloadHex.Equals(input.SignerPayloadHex))
                ) && 
                (
                    this.Fee == input.Fee ||
                    (this.Fee != null &&
                    this.Fee.Equals(input.Fee))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignerPayloadJSON != null)
                {
                    hashCode = (hashCode * 59) + this.SignerPayloadJSON.GetHashCode();
                }
                if (this.SignerPayloadRaw != null)
                {
                    hashCode = (hashCode * 59) + this.SignerPayloadRaw.GetHashCode();
                }
                if (this.SignerPayloadHex != null)
                {
                    hashCode = (hashCode * 59) + this.SignerPayloadHex.GetHashCode();
                }
                if (this.Fee != null)
                {
                    hashCode = (hashCode * 59) + this.Fee.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
